name: Render and deploy github pages
on: 
  push:
  pull_request:

jobs:
  render-and-deploy-gh-page:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "Check directory"
      run: |
        echo "Listing root"
        ls -l
    - name: "Install Quarto and render"
      uses: yogasgm/quartotest.github.io@gh-pages

    - name: "Check directory"
      run: |
        echo "Listing root"
        ls -l
        echo "Listing site/*:"
        ls -l _site/*/
        echo "Listing site/*:"
        ls -l _site/*/*
    
    - name: "Quarto check"
      run: |
        quarto check
    - name: "List users"
      run: |
        cat /etc/passwd
    - name: "Check directory"
      run: |
        echo "Listing root"
        ls -l
        echo "Listing site/*:"
        ls -l _site/*/
        echo "Listing site/*:"
        ls -l _site/*/*
    - name: "Deploy to gh-pages"
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

    - name: "Check directory"
      run: |
        echo "Listing root"
        ls -l
        echo "Listing site/*:"
        ls -l _site/*
        echo "Listing site/*/*:"
        ls -l _site/*/*
